Controllers/BossesController.cs
using HeadHunter.Models;
using HeadHunter.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace HeadHunter.Controllers
{
    [Authorize(Roles = "boss")]
    public class BossesController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private ApplicationContext _db;

        public BossesController(UserManager<User> userManager, SignInManager<User> signInManager, ApplicationContext db)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _db = db;
        }
        [HttpGet]
        public IActionResult BossesProfile()
        {
            User user = _db.Users.FirstOrDefault(u => u.Id == _userManager.GetUserId(User));
            BossesProfileViewModel viewModel = new BossesProfileViewModel
            {
                UserId = user.Id,
                Email = user.Email,
                Nickname = user.UserName,
                Name = user.Name,
                Surname = user.Surname,
                PhoneNumber = user.PhoneNumber,
                CompanyName = user.CompanyName,
                LinkImg = user.LinkImg,
                Vacancies = _db.Vacancies.Where(v => v.UserId == user.Id).OrderByDescending(v => v.DateOfUpdate).ToList()
            };
            ViewBag.CurrentUserId = _userManager.GetUserId(User);
            return View(viewModel);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(BossesProfileViewModel model)
        {
            User user = await _db.Users.FirstOrDefaultAsync(u => u.Id == model.UserId);
            if (ModelState.IsValid)
            {
                string filename;
                if (model.File != null)
                {
                    filename = model.Nickname + Path.GetExtension(model.File.FileName);
                    System.IO.File.Delete(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\avatars\\" + user.LinkImg));
                    user.LinkImg = filename;
                    using (var stream = new FileStream(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\avatars\\" + filename), FileMode.Create))
                    {
                        await model.File.CopyToAsync(stream);
                    }
                }
                user.Email = model.Email;
                user.UserName = model.Nickname;
                user.Surname = model.Surname;
                user.Name = model.Name;
                user.CompanyName = model.CompanyName;
                user.PhoneNumber = model.PhoneNumber;
                await _db.SaveChangesAsync();
            return RedirectToAction("BossesProfile");
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult AddVacancy()
        {
            List<CategoryVacancy> categories = _db.CategoryVacancies.ToList();
            categories.Remove(categories.FirstOrDefault(c => c.Id == "default"));
            ViewBag.Categories = categories;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddVacancy(Vacancy vacancy)
        {
            if (vacancy.ExperienceFrom > vacancy.ExperienceTo && vacancy.ExperienceTo != 0)
            {
                ModelState.AddModelError("ExperienceTo", "Опыт работы ДО не может быть меньше ОТ");
            }
            if (ModelState.IsValid)
            {
                vacancy.Id = Guid.NewGuid().ToString();
                vacancy.DateOfUpdate = DateTime.Now;
                vacancy.UserId = _userManager.GetUserId(User);
                vacancy.Agreement = true;
                _db.Vacancies.Add(vacancy);
                await _db.SaveChangesAsync();
                return RedirectToAction("BossesProfile");
            }
            List<CategoryVacancy> categories = _db.CategoryVacancies.ToList();
            categories.Remove(categories.FirstOrDefault(c => c.Id == "default"));
            ViewBag.Categories = categories;

            return View(vacancy);
            
        }

        [HttpPost]
        public async Task<IActionResult> AddCategory(string text)
        {
            CategoryVacancy category = new CategoryVacancy { Id = Guid.NewGuid().ToString(), Name = text };
            _db.CategoryVacancies.Add(category);
            await _db.SaveChangesAsync();
            return Json(category);
        }

        public async Task<IActionResult> UpdateVacancy(string id)
        {
            Vacancy vacancy = _db.Vacancies.Find(id);
            vacancy.DateOfUpdate = DateTime.Now;
            _db.Vacancies.Update(vacancy);
            await _db.SaveChangesAsync();
            return Json(vacancy);
        }

        public async Task<IActionResult> Disagreement(string id)
        {
            Vacancy vacancy = _db.Vacancies.Find(id);
            vacancy.Agreement = !vacancy.Agreement;
            _db.Vacancies.Update(vacancy);
            await _db.SaveChangesAsync();
            return Json(vacancy);
        }

        public IActionResult EditVacancy(string id)
        {
            Vacancy vacancy = _db.Vacancies.Find(id);
            ViewBag.Categories = _db.CategoryVacancies.ToList();
            return View(vacancy);
        }

        [HttpPost]
        public async Task<IActionResult> EditVacancy(Vacancy vacancy)
        {
            if (vacancy.ExperienceFrom > vacancy.ExperienceTo && vacancy.ExperienceTo != 0)
            {
                ModelState.AddModelError("ExperienceTo", "Опыт работы ДО не может быть меньше ОТ");
            }
            if (ModelState.IsValid)
            {
                vacancy.UserId = _userManager.GetUserId(User);
                vacancy.DateOfUpdate = DateTime.Now;
                _db.Update(vacancy);
                await _db.SaveChangesAsync();
                return RedirectToAction("BossesProfile");
            }
            ViewBag.Categories = _db.CategoryVacancies.ToList();
            return View(vacancy);
        }
        
    }
}

Controllers/PublicController.cs
using HeadHunter.Enums;
using HeadHunter.Models;
using HeadHunter.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HeadHunter.Controllers
{
    [Authorize]
    public class PublicController : Controller
    {
        private readonly UserManager<User> _userManager;
        private ApplicationContext _context;

        public PublicController(UserManager<User> userManager, ApplicationContext context)
        {
            _userManager = userManager;
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult ResumeDetails(string resumeId)
        {
            var resume = _context.Resumes.Find(resumeId);
            ViewBag.Category = _context.CategoryVacancies.Find(resume.CategoryId);
            ViewBag.Work = _context.WorkExpiriences.Where(e => e.ResumeId == resumeId).ToList();
            ViewBag.Education = _context.EducationExpiriences.Where(e => e.ResumeId == resumeId).ToList();
            ViewBag.Courses = _context.CoursesExpiriences.Where(e => e.ResumeId == resumeId).ToList();
            return View(resume);
        }
        public IActionResult VacancyDetails(string vacancyId)
        {
            Vacancy vacancy = _context.Vacancies.Include(v => v.User).FirstOrDefault(v => v.Id == vacancyId);
            ViewBag.CategoryName = _context.CategoryVacancies.Find(vacancy.CategoryVacancyId).Name;
            return View(vacancy);
        }
        public IActionResult Publications(string searchString, string categoryId, SortState sortOrder = SortState.DateDesc, int page = 1)
        {
            int pageSize = 20;
            string userId = _userManager.GetUserId(User);
            PublicationsViewModel rlvm = new PublicationsViewModel()
            {
                CategoryId = categoryId
            };
            ViewBag.DateSort = sortOrder == SortState.DateAsc ? SortState.DateDesc : SortState.DateAsc;
            ViewBag.WageSort = sortOrder == SortState.WageAsc ? SortState.WageDesc : SortState.WageAsc;


            if (User.IsInRole("applicant"))
            {
                var vacancies = _context.Vacancies.Include(r => r.User).Where(r => r.Agreement == true);
                if (!String.IsNullOrEmpty(searchString))
                {
                    searchString = searchString.ToLower();
                    vacancies = vacancies.Where(v => v.Name.ToLower().Contains(searchString));
                }
                if (!String.IsNullOrEmpty(categoryId))
                {
                    vacancies = vacancies.Where(p => p.CategoryVacancyId.Contains(categoryId));
                }
                switch (sortOrder)
                {
                    case SortState.DateAsc:
                        vacancies = vacancies.OrderBy(s => s.DateOfUpdate);
                        break;
                    case SortState.WageAsc:
                        vacancies = vacancies.OrderBy(s => s.Wage);
                        break;
                    case SortState.WageDesc:
                        vacancies = vacancies.OrderByDescending(s => s.Wage);
                        break;
                    default:
                        vacancies = vacancies.OrderByDescending(s => s.DateOfUpdate);
                        break;
                }
                rlvm.PageViewModel = new PageViewModel(vacancies.Count(), page, pageSize);
                rlvm.Vacancies = vacancies.Skip((page - 1) * pageSize).Take(pageSize);
                ViewBag.PageCount = (vacancies.Count() + pageSize - 1) / pageSize;
                ViewBag.MyResumes = _context.Resumes.Where(r => r.UserId == userId).ToList();
            }
            else
            {
                var resumes = _context.Resumes.Include(r => r.User).Where(r => r.Published == true);
                if (!String.IsNullOrEmpty(searchString))
                {
                    searchString = searchString.ToLower();
                    resumes = resumes.Where(v => v.JobTitle.ToLower().Contains(searchString));
                }
                if (!String.IsNullOrEmpty(categoryId))
                {
                    resumes = resumes.Where(p => p.CategoryId.Contains(categoryId));
                }
                switch (sortOrder)
                {
                    case SortState.DateAsc:
                        resumes = resumes.OrderBy(s => s.UpdateDate);
                        break;
                    case SortState.WageAsc:
                        resumes = resumes.OrderBy(s => s.Wage);
                        break;
                    case SortState.WageDesc:
                        resumes = resumes.OrderByDescending(s => s.Wage);
                        break;
                    default:
                        resumes = resumes.OrderByDescending(s => s.UpdateDate);
                        break;
                }

                rlvm.PageViewModel = new PageViewModel(resumes.Count(), page, pageSize);
                rlvm.Resumes = resumes.Skip((page - 1) * pageSize).Take(pageSize);
                ViewBag.PageCount = (resumes.Count() + pageSize - 1) / pageSize;
                ViewBag.MyVacancies = _context.Vacancies.Where(r => r.UserId == userId).ToList();
            }

            ViewBag.Categories = _context.CategoryVacancies.ToList();
            return View(rlvm);
        }
        public IActionResult BossesProfile(string userId)
        {
            User user = _context.Users.FirstOrDefault(u => u.Id == userId);
            BossesProfileViewModel viewModel = new BossesProfileViewModel
            {
                UserId = user.Id,
                Email = user.Email,
                Nickname = user.UserName,
                Name = user.Name,
                Surname = user.Surname,
                PhoneNumber = user.PhoneNumber,
                CompanyName = user.CompanyName,
                LinkImg = user.LinkImg,
                Vacancies = _context.Vacancies.Where(v => v.UserId == user.Id).Where(v => v.Agreement == true).OrderByDescending(v => v.DateOfUpdate).ToList()
            };
            ViewBag.CurrentUserId = _userManager.GetUserId(User);
            return View(viewModel);
        }
        public IActionResult ApplicantProfile(string userId)
        {
            User user = _context.Users.FirstOrDefault(u => u.Id == userId);
            ApplicantProfileViewModel viewModel = new ApplicantProfileViewModel
            {
                UserId = user.Id,
                Email = user.Email,
                Nickname = user.UserName,
                Name = user.Name,
                Surname = user.Surname,
                PhoneNumber = user.PhoneNumber,
                LinkImg = user.LinkImg,
                Resumes = _context.Resumes.Where(v => v.UserId == user.Id).Where(r => r.Published == true).OrderByDescending(v => v.UpdateDate).ToList()
            };
            ViewBag.CurrentUserId = _userManager.GetUserId(User);
            return View(viewModel);
        }

        public IActionResult PersonalChat(string chatId)
        {
            User user = _context.Users.FirstOrDefault(u => u.Id == _userManager.GetUserId(User));
            Chat chat = _context.Chats.Include(u => u.FirstUser).Include(u => u.SecondUser).FirstOrDefault(c => c.Id == chatId);

            if (chat == null)
            {
                return RedirectToAction("Publications");
            }
            ViewBag.CurrentUser = user.Id;
            ViewBag.Messages = _context.Messages.Where(m => m.ChatId == chat.Id);
            return View(chat);
        }

        [HttpPost]
        public async Task<IActionResult> CreateChat(string vacancyId, string resumeId)
        {
            Chat existChat = await _context.Chats.FirstOrDefaultAsync(c => c.VacancyId == vacancyId && c.ResumeId == resumeId);
            if (existChat != null)
            {
                return Json(new { chatId = existChat.Id });
            }
            Vacancy vacancy = _context.Vacancies.FirstOrDefault(v => v.Id == vacancyId);
            Resume resume = _context.Resumes.FirstOrDefault(v => v.Id == resumeId);
            User firstUser = _context.Users.FirstOrDefault(u => u.Id == vacancy.UserId);
            User secondUser = _context.Users.FirstOrDefault(u => u.Id == resume.UserId);
            Chat chat = new Chat
            {
                Id = Guid.NewGuid().ToString(),
                FirstUserId = firstUser.Id,
                SecondUserId = secondUser.Id,
                VacancyId = vacancy.Id,
                ResumeId = resume.Id
            };
            _context.Chats.Add(chat);
            await _context.SaveChangesAsync();
            return Json(new { chatId = chat.Id });
        }

        [HttpPost]
        public async Task<IActionResult> SendMessage(string senderId, string chatId, string text)
        {
            Message message = new Message {
                Id = Guid.NewGuid().ToString(),
                ChatId = chatId,
                SenderId = senderId,
                Text = text.Trim(),
                DateOfSending = DateTime.Now
            };

            _context.Messages.Add(message);
            await _context.SaveChangesAsync();
            return Json(message);
        }

        [HttpPost]
        public IActionResult CheckNewMessages(string chatId, int count)
        {
            Message[] messages = _context.Messages.Where(m => m.ChatId == chatId).OrderBy(m => m.DateOfSending).ToArray();
            return Json(messages.Skip(count));
        }

        public IActionResult Chats()
        {
            List<Chat> chats;

Views/Applicant/Profile.cshtml
@model ApplicantProfileViewModel
@{
    ViewBag.Tittle = "Profile";
    Layout = "_Layout";
}

<div class="row">
    <div class="col-5 text-center">
        <img src="~/avatars/@Model.LinkImg" width="200" height="200" class="border border-dark rounded-circle p-2" />
    </div>
    <div class="col-7 pt-3">
        <p>Nickname: <b style="font-size:25px;">@Model.Nickname</b></p>
        <p>Surname: @Model.Surname</p>
        <p>Name: @Model.Name</p>
        <p>Email: @Model.Email</p>
        <p>Phone number: @Model.PhoneNumber</p>
        <button type="button" class="btn btn-light border-dark" data-toggle="modal" data-target="#EditModal">Edit</button>
    </div>
</div>
<div class="mt-5">
    <a asp-controller="Applicant" asp-action="AddResume" class="btn btn-light border-dark mb-3">Добавить резюме</a>
    @if (Model.Resumes.Count > 0)
    {
        <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th style="width: 50%;">Job title</th>
                    <th style="width: 25%;">Update Date</th>
                    <th style="width: 25%;"></th>
                </tr>
            </thead>
            @foreach (var item in Model.Resumes)
            {
                <tr onclick="details('@item.Id')" style="cursor:pointer;">
                    <td style="width: 50%;">@item.JobTitle</td>
                    <td id="date-@item.Id" style="width: 25%;">@item.UpdateDate.ToUniversalTime()</td>
                    <td style="width: 25%;">
                        <a class="btn btn-light border-dark" onclick="Update('@item.Id')">Обновить</a>
                        <a asp-controller="Applicant" asp-action="EditResume" class="btn btn-light border-dark" asp-route-resumeId="@item.Id">Редактировать</a><br />
                        @if (item.Published)
                        {
                            <a id="buttonAgreement-@item.Id" class="btn btn-light border-dark mt-1" onclick="Disagreement('@item.Id')">Снять с публикации</a>
                        }
                        else
                        {
                            <a id="buttonAgreement-@item.Id" class="btn btn-light border-dark mt-1" onclick="Disagreement('@item.Id')">Добавить в публикации</a>
                        }
                    </td>
                </tr>
            }
        </table>
    }
    else
    {
        <p class="text-center font-weight-bold">У вас еще нет резюме</p>
    }
</div>

<div id="false" class="alert alert-success position-fixed" role="alert" style="display: none; bottom: 0; right: 20px;">
    Резюме снято с публикации
</div>
<div id="true" class="alert alert-success position-fixed" role="alert" style="display: none; bottom: 0; right: 20px;">
    Резюме добавлено в публикации
</div>


<div class="modal fade" id="EditModal" tabindex="-1" role="dialog" aria-labelledby="EditModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="EditModalLabel">Редактирование</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="m-3">
                <form asp-controller="Bosses" asp-action="Edit" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="UserId" value="@Model.UserId" />
                    <label asp-for="File" class="control-label">Изменение аватарки</label>
                    <input asp-for="File" type="file" class="form-control" />
                    <div class="form-group">
                        <label asp-for="Email" class="control-label">Почта</label>
                        <input asp-for="Email" class="form-control" value="@Model.Email" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Nickname" class="control-label">Никнейм</label>
                        <input asp-for="Nickname" class="form-control" value="@Model.Nickname" />
                        <span asp-validation-for="Nickname" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Surname" class="control-label">Фамилия</label>
                        <input asp-for="Surname" class="form-control" />
                        <span asp-validation-for="Surname" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label">Имя</label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PhoneNumber" class="control-label">Номер телефона</label>
                        <input asp-for="PhoneNumber" class="form-control" />
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                    <button id="editModalButton" type="submit" class="btn btn-primary ml-3">Сохранить</button>
                </form>

                @section Scripts
                {
                    @{
                        await Html.RenderPartialAsync("_ValidationScriptsPartial");
                    }
                    <script>
                        function details(resumeId) {
                            window.location.href = '@Url.Action("ResumeDetails","Public")?resumeId=' + resumeId;
                        }
                        function Update(id) {
                            event.stopPropagation();
                            $.ajax({
                                url: '@Url.Action("UpdateResume", "Applicant")',
                                type: 'POST',
                                data: { 'id': id },
                                success: function (data) {
                                    console.log(data);
                                    let dateTime = new Date(data['updateDate']).toLocaleString();
                                    $('#date-' + id).text(dateTime);
                                },
                            });
                        }
                        function Disagreement(id) {
                            event.stopPropagation();
                            $.ajax({
                                url: '@Url.Action("Disagreement", "Applicant")',
                                type: 'POST',
                                data: { 'id': id },
                                success: function (data) {
                                    console.log(data);
                                    if (data['published'] == false) {
                                        $('#buttonAgreement-' + id).text('Добавить в публикации');
                                        $("#false").show();
                                        setTimeout(function () { $("#false").hide(); }, 3000);
                                    }
                                    else {
                                        $('#buttonAgreement-' + id).text('Снять с публикации');
                                        $("#true").show();
                                        setTimeout(function () { $("#true").hide(); }, 3000);
                                    }
                                },
                            });
                        }
                    </script>
                }
            </div>
        </div>
    </div>
</div>